# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-11 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeInicioDeuda', models.DateField()),
                ('montoDeuda', models.IntegerField(default=0)),
                ('acreedor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidoPaterno', models.CharField(max_length=200)),
                ('apellidoMaterno', models.CharField(max_length=200)),
                ('estadoCivil', models.CharField(choices=[('SOL', 'SOLTERO'), ('CAS', 'CASADO'), ('VIU', 'VIUDO'), ('DIV', 'DIVORCIADO')], max_length=3)),
                ('fechaDeNacimiento', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='deuda',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deudas.Deudor'),
        ),
    ]
